# Generated by Django 5.2.11 on 2026-02-05 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypage',
            name='desription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diarypage',
            name='diasolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='diarypage',
            name='glucose',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='diarypage',
            name='systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10),
        ),
    ]
