# Generated by Django 5.2.11 on 2026-02-05 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_diarypage_desription_diarypage_diasolic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarypage',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='diarypage',
            old_name='diasolic',
            new_name='diastolic',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='numbers_passport',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='series_passport',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='snils',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
