# Generated by Django 5.2.11 on 2026-02-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_desription_diarypage_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='patronymic',
        ),
    ]
