# Generated by Django 5.2.11 on 2026-02-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_surname_user_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
