# Generated by Django 5.2.11 on 2026-02-06 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_patronymic_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='card_number',
            field=models.PositiveSmallIntegerField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='numbers_passport',
            field=models.PositiveSmallIntegerField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='series_passport',
            field=models.PositiveSmallIntegerField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
