# Generated by Django 5.2.11 on 2026-02-06 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_medicalrecord_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='numbers_passport',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='series_passport',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='snils',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
