# Generated by Django 5.2.11 on 2026-02-06 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_medicalrecord_numbers_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='card_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
