# Generated by Django 5.2.11 on 2026-02-06 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_medicalrecord_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='snils',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
