# Generated by Django 5.2.11 on 2026-02-06 07:24

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_medicalrecord_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='card_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='numbers_passport',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='series_passport',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='snils',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
    ]
